---
- hosts: [hosts]
  gather_facts: true
  remote_user: root
  become: true
  pre_tasks:
    - name: installing python
      package:
        name: python3
        state: present 
  roles:
    - role: ./
