---
# tasks file for DevOps Install
- name: Install DevOps-Install packages
  yum:
    name:
      - firewalld
      - vim
      - htop
      - git
      - wget
      - curl
      - tree
      - cockpit
      - code
    state: present
- name: Make sure firewalld is running
  systemd:
    state: started
    enabled: yes
    name: firewalld
- name: enable https
  firewalld:
    service: https
    permanent: yes
    state: enabled
  notify: reload firewalld
- name: enable http
  firewalld:
    service: http
    permanent: yes
    state: enabled
  notify: reload firewalld
- name: enable cockpit port
  firewalld:
    port: 9090/tcp
    permanent: yes
    state: enabled
  notify: reload firewalld
- name: enable tools ssh
  firewalld:
    port: 22/tcp
    permanent: yes
    state: enabled
  notify: reload firewalld
- import_tasks: docker_centos.yml