---
# tasks file for DevOps Install
- name: Install required packages
  apt:
    pkg:
    - vim
    - htop
    - git
    - sudo
    - wget
    - curl
    - tree
    - cockpit
    - code
- import_tasks: docker_ubuntu.yml